{% set name = "bmi-wavewatch3" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/bmi-wavewatch3/archive/v{{ version }}.tar.gz
  sha256: bf3dceafed582517b6e94e1261dcf7d0d713e0b0bdfd5ad8b1a347415637aa17

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - ww3 = bmi_wavewatch3.cli:ww3


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bmipy
    - cfgrib
    - click
    - tomli
    - matplotlib-base
    - tqdm
    - xarray

test:
  imports:
    - bmi_wavewatch3
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - ww3 --version
    - ww3 --help
    - ww3 info --all
    - ww3 fetch
    - ww3 url
    - ww3 clean --cache-dir=.

about:
  home: https://github.com/csdms/bmi-wavewatch3
  summary: WAVEWATCH III data in Python
  description: |
    The bmi_wavewatch3 Python package provides both a command line
    interface and a programming interface for downloading and working
    with WAVEWATCH III data.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  # The doc_url and dev_url are optional.
  doc_url: https://github.com/csdms/bmi-wavewatch3/blob/main/README.rst
  dev_url: https://github.com/csdms/bmi-wavewatch3

extra:
  recipe-maintainers:
    - mcflugen
